FROM nvcr.io/nvidia/tritonserver:25.05-py3

RUN apt-get update && apt-get install -y --no-install-recommends \
    ffmpeg \
    libsndfile1 \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --no-cache-dir \
    Cython \
    packaging \
    librosa \
    soundfile \
    scipy \
    && python3 -m pip install --no-cache-dir \
    "git+https://github.com/NVIDIA/NeMo.git@main#egg=nemo_toolkit[asr]"

WORKDIR /models
